import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { parseSegment } from './shared/slug.ts'

/**
 * Serves `/{lang}/{slug}-{code}/` from that language's entry page while developing.
 *
 * In production those 580 files exist on disk, written after the build by
 * `tools/build-pages.mjs`. Without this middleware every one of those URLs would 404 under
 * `yarn dev` and work once deployed, which is the worst way round: the failure shows up only
 * where it is hardest to notice and impossible to debug.
 *
 * The code is checked against the pantry so an unknown one 404s here exactly as it will in
 * production, rather than silently rendering the front page and looking like a bug in the app.
 */
function knownCodes(): Set<string> {
  const data = JSON.parse(
    readFileSync(resolve(import.meta.dirname, 'public/pantry/data/indicators.json'), 'utf8'),
  ) as { municipalities: Array<{ code: string }> }
  return new Set(data.municipalities.map((m) => m.code))
}

/** `/{lang}/{segment}/` and the code it names, or null when the path is something else. */
function municipalityRequest(url: string): { lang: string; code: string | null } | null {
  const path = url.split('?')[0] ?? ''
  const match = /^\/(sv|en)\/([^/]+)\/?$/.exec(path)
  if (!match?.[1] || !match[2]) return null
  return { lang: match[1], code: parseSegment(match[2]) }
}

/**
 * The `/*` rules out of a Cloudflare `_headers` file, as plain pairs.
 *
 * Only the catch-all section is read, because that is the only section this project writes. A
 * per-path rule appearing in `_headers` and being silently ignored here would be the drift this
 * whole plugin exists to prevent, so it throws instead.
 */
export function parseHeaders(text: string): Array<[string, string]> {
  const pairs: Array<[string, string]> = []
  let inCatchAll = false
  for (const raw of text.split('\n')) {
    const line = raw.trimEnd()
    if (line.trim() === '' || line.trimStart().startsWith('#')) continue
    if (!/^\s/.test(line)) {
      if (line.trim() !== '/*') {
        throw new Error(
          `_headers has a rule for '${line.trim()}'; the preview server only applies '/*'`,
        )
      }
      inCatchAll = true
      continue
    }
    if (!inCatchAll) continue
    const at = line.indexOf(':')
    if (at === -1) continue
    pairs.push([line.slice(0, at).trim(), line.slice(at + 1).trim()])
  }
  return pairs
}

function municipalityPages(): Plugin {
  return {
    name: 'municipality-pages',

    /**
     * `vite preview` has its own SPA fallback and would answer 200 with the root page for a
     * path that does not exist, while Cloudflare Pages — having no such file — answers 404. The
     * browser tests run against preview, so without this the suite would assert the preview
     * server's behaviour rather than the one that ships.
     *
     * Registered BEFORE Vite's own middlewares, not after. By the time the internal ones have
     * run, `/en/atlantis-9999/` has already been rewritten to `/index.html` by the SPA fallback
     * and the original path is gone — which is exactly how the first attempt at this managed to
     * 404 the language entry pages and let the unknown ones through.
     *
     * The rule is the file system, not a list of codes: 404 when the document a static host
     * would serve is not there. That cannot drift from what Cloudflare does, because it is the
     * same question.
     */
    configurePreviewServer(server) {
      /**
       * The response headers Cloudflare will serve, served here too.
       *
       * Without this the browser suite would exercise a site with no Content Security Policy and
       * pass, while the deployed site ran under one that could block its own bundle — and there
       * is no staging environment in which anybody would find out. The policy is generated by
       * `tools/build-pages.mjs` from the built files, so reading it back from `dist` tests the
       * real thing rather than a second copy of the intent.
       */
      const headersFile = resolve(import.meta.dirname, 'dist/_headers')
      const headers = existsSync(headersFile)
        ? parseHeaders(readFileSync(headersFile, 'utf8'))
        : (() => {
            throw new Error('dist/_headers is missing; run the build before previewing')
          })()
      server.middlewares.use((_req, res, next) => {
        for (const [name, value] of headers) res.setHeader(name, value)
        next()
      })

      server.middlewares.use((req, res, next) => {
        const request = municipalityRequest(req.url ?? '')
        if (!request) return next()
        const path = (req.url ?? '').split('?')[0] ?? ''
        const file = resolve(import.meta.dirname, `dist${path.replace(/\/?$/, '/')}index.html`)
        if (existsSync(file)) return next()
        res.statusCode = 404
        res.setHeader('Content-Type', 'text/plain; charset=utf-8')
        res.end(`No municipality page at ${path}`)
      })
    },

    configureServer(server) {
      let codes: Set<string> | null = null
      server.middlewares.use((req, res, next) => {
        const request = municipalityRequest(req.url ?? '')
        if (!request) return next()
        codes ??= knownCodes()

        if (!request.code || !codes.has(request.code)) {
          // Not `next()`. Vite's SPA fallback would answer 200 with the root page, while
          // production has no such file and answers 404 — and a route that only fails once
          // deployed is the hardest kind to notice.
          res.statusCode = 404
          res.setHeader('Content-Type', 'text/plain; charset=utf-8')
          res.end(`No municipality page at ${req.url}`)
          return
        }

        const html = readFileSync(
          resolve(import.meta.dirname, `${request.lang}/index.html`),
          'utf8',
        )
        server.transformIndexHtml(req.url ?? '/', html).then(
          (transformed) => {
            res.setHeader('Content-Type', 'text/html; charset=utf-8')
            res.end(transformed)
          },
          () => next(),
        )
      })
    },
  }
}

/**
 * Three entry pages, not one. The language lives in the path (`/sv/`, `/en/`) so each page can
 * declare its own `lang` and its own title before any JavaScript runs — which is what a search
 * engine indexes and what a screen reader announces on arrival. The root page is a static
 * language picker and must be listed here too, or it never reaches `dist` and the bare domain
 * 404s in production while working perfectly in development.
 */
export default defineConfig({
  plugins: [react(), municipalityPages()],
  publicDir: 'public',
  build: {
    rollupOptions: {
      input: {
        root: resolve(import.meta.dirname, 'index.html'),
        sv: resolve(import.meta.dirname, 'sv/index.html'),
        en: resolve(import.meta.dirname, 'en/index.html'),
      },
    },
  },
})
