#!/usr/bin/env node
/**
 * The 290 preview cards, one per municipality.
 *
 * **Run deliberately, with `yarn cards` — never from `yarn build`.** Text rendering differs
 * between macOS and Linux, so the same card drawn on a laptop and in CI is not byte-identical.
 * Wiring this into the build would mean every CI run produced a diff against the committed
 * files. The PNGs in `public/share/` are the artefact; this is how they were made.
 *
 * **Nothing on the card changes when the data does.** It carries the municipality's name and the
 * site's, and no figure — so a monthly refresh never rewrites 290 binaries. A card with a
 * headline number on it would cost the same 4.7 MB and then churn all of it every month, which
 * is roughly 56 MB of git history a year for a number nobody reads twice.
 *
 * One card serves both languages, because all 290 municipality names are identical in Swedish
 * and English. `shared/slug.test.ts` asserts that rather than assuming it.
 *
 * Rasterised rather than shipped as SVG: checked on 2026-09-15, no platform documents SVG
 * support for `og:image`. Facebook's image documentation gives dimensions and says nothing about
 * formats, Slack's unfurling documentation says nothing either, and X's is behind a paywall.
 * Shipping SVG would be betting on behaviour three primary sources decline to promise.
 */
import { chromium } from 'playwright'
import { mkdirSync, readFileSync, writeFileSync, readdirSync, rmSync } from 'node:fs'
import { readPantry } from './read-pantry.mjs'
import { join, resolve } from 'node:path'

/** 1200x630 is Facebook's own recommendation and the 1.91:1 every platform crops to. */
const WIDTH = 1200
const HEIGHT = 630

const root = resolve(import.meta.dirname, '..')
const outDir = join(root, 'public/share')

/** One line, not two: the name is the same in both languages, which is why it was chosen. */
const SITE = 'Atlas 290'

/**
 * Deliberately one palette rather than following a colour scheme: the card is its own artwork,
 * seen inside somebody else's chat client, and has no idea what theme that client is in.
 */
function card(name) {
  return `<!doctype html>
<html lang="sv"><meta charset="utf-8" />
<style>
  html, body { margin: 0; width: ${WIDTH}px; height: ${HEIGHT}px; }
  body {
    box-sizing: border-box;
    padding: 90px;
    background: #16181a;
    color: #f7f7f5;
    font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
  }
  h1 { font-size: 104px; line-height: 1.05; margin: 0; font-weight: 700; letter-spacing: -0.02em; }
  .site { font-size: 34px; color: #b9bfc7; margin: 0; }
  .rule { height: 8px; width: 160px; background: #8ab8e8; border-radius: 4px; margin: 0 0 40px; }
</style>
<body>
  <div><div class="rule"></div><h1>${escapeHtml(name)}</h1></div>
  <p class="site">${SITE}</p>
</body></html>`
}

function escapeHtml(s) {
  return s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c])
}

const data = readPantry()

mkdirSync(outDir, { recursive: true })
// Anything already there that no municipality claims is stale — a code SCB retired, or a
// half-finished run. Removed rather than left to rot beside the real ones.
const wanted = new Set(data.municipalities.map((m) => `${m.code}.png`))
for (const file of readdirSync(outDir)) {
  if (file.endsWith('.png') && !wanted.has(file)) rmSync(join(outDir, file))
}

const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: WIDTH, height: HEIGHT } })
const started = Date.now()
for (const m of data.municipalities) {
  await page.setContent(card(m.name.sv), { waitUntil: 'load' })
  await page.screenshot({ path: join(outDir, `${m.code}.png`) })
}
await browser.close()

const bytes = readdirSync(outDir)
  .filter((f) => f.endsWith('.png'))
  .reduce((total, f) => total + readFileSync(join(outDir, f)).length, 0)

writeFileSync(
  join(outDir, 'README.md'),
  `# Preview cards\n\nGenerated by \`yarn cards\` (tools/build-cards.mjs), committed, and regenerated\nonly on purpose. They carry no figures, so a data refresh never invalidates them.\n\n${data.municipalities.length} cards, ${WIDTH}x${HEIGHT}, ${(bytes / 1048576).toFixed(1)} MB.\n`,
)

console.log(
  `${data.municipalities.length} cards in ${((Date.now() - started) / 1000).toFixed(1)}s, ` +
    `${(bytes / 1048576).toFixed(1)} MB total`,
)
